<a href="https://colab.research.google.com/github/Sarith99/ML_Courses_Practicals/blob/main/Eager_execution_vs_Graph_execution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import tensorflow as tf
import timeit

In [13]:
def eager_funct(a):
  result = a ** 2 
  print(result)
  return result

x = tf.constant([1.0, 3.0, 4.0, 5.0])
eager_funct(x)

tf.Tensor([ 1.        9.       16.       24.999998], shape=(4,), dtype=float32)


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 1.      ,  9.      , 16.      , 24.999998], dtype=float32)>

In [14]:
x = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0])
graph_function = tf.function(eager_funct)
graph_function(x)

Tensor("pow:0", shape=(5,), dtype=float32)


<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 1.,  4.,  9., 16., 25.], dtype=float32)>

In [16]:
print("Eager Time: ", timeit.timeit(lambda: eager_funct(x), number=1))
print("Graph Time: ", timeit.timeit(lambda: graph_function(x), number=1))

tf.Tensor([ 1.        4.        9.       16.       24.999998], shape=(5,), dtype=float32)
Eager Time:  0.001106123999988995
Graph Time:  0.007750591999865719


############################################################################################################################################################################################################################################################################################################################################################################################

In [17]:
from tensorflow.keras import Input, Model
from tensorflow.keras.layers import Flatten, Dense

In [18]:
# Model Building
inputs = Input(shape = (28, 28))
x = Flatten()(inputs)
x = Dense(256, "relu")(x)
x = Dense(256, "relu")(x)
x = Dense(256, "relu")(x)
outputs = Dense(10, "softmax")(x)

In [19]:
input_data = tf.random.uniform([100, 28, 28])

In [20]:
# Eager Execution
eager_model = Model(inputs = inputs, outputs = outputs)
print("Eager Time: ", timeit.timeit(lambda: eager_model(input_data), number=10000))

Eager Time:  28.919566974999952


In [22]:
# Graph Execution
graph_model = tf.function(eager_model)
print("Graph Time", timeit.timeit(lambda: graph_model(input_data), number=10000))

Graph Time 7.718085970999709
