<a href="https://colab.research.google.com/github/Sarith99/ML_Courses_Practicals/blob/main/Mastering_Tensorflow_Tensors_In_5_Steps.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# You can create Tensor objects with the `tf.constant` function:
x = tf.constant([[1, 2, 3, 4 ,5]])
# You can create Tensor objects only consisting of 1s with the `tf.ones` function:
y = tf.ones((3,5))
# You can create Tensor objects only consisting of 0s with the `tf.zeros` function:
z = tf.zeros((2,5))
# You can use the `tf.range()` function to create Tensor objects:
q = tf.range(start=1, limit=6, delta=2)

print(x)
print(y)
print(z)
print(q)

tf.Tensor([[1 2 3 4 5]], shape=(1, 5), dtype=int32)
tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(3, 5), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(2, 5), dtype=float32)
tf.Tensor([1 3 5], shape=(3,), dtype=int32)


In [35]:
a = tf.constant([[1, 2, "Sarith", 3]])
print(a)

ValueError: ignored

In [4]:
Three_lvl_nested_list = [[[1,2,3],
                          [4,5,6]],
                         [[0,9,8],
                          [7,6,5]]]

rank_three_tensor = tf.constant(Three_lvl_nested_list)
print(rank_three_tensor)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[0 9 8]
  [7 6 5]]], shape=(2, 2, 3), dtype=int32)


**Rank System and Dimension**

In [5]:
# We can view the number of diamensions that our `rank_3_tensor` object currently has with the `.ndim` attribute.
tensor_Ndim = rank_three_tensor.ndim
print("The number of diamension in the tensor object: ", tensor_Ndim)

The number of diamension in the tensor object:  3


**Shape**

In [6]:
tensor_shape = rank_three_tensor.shape
print("The shape of our Tensor object is: ", tensor_shape)

The shape of our Tensor object is:  (2, 2, 3)


**Size**

In [7]:
tensor_size = tf.size(rank_three_tensor).numpy()
print("The size of our tensor object is: ", tensor_size)

The size of our tensor object is:  12


**Dtypes**

In [8]:
tensor_dtype = rank_three_tensor.dtype
print("The data type of this Tensor object is: ", tensor_dtype)

The data type of this Tensor object is:  <dtype: 'int32'>


### **Operations with Tensors**

**Indexing**

In [9]:
single_level_nested_list = [0, 1, 2, 3, 4, 5, 6, 7]
rank_1_tensor = tf.constant(single_level_nested_list)
print(rank_1_tensor)

tf.Tensor([0 1 2 3 4 5 6 7], shape=(8,), dtype=int32)


In [10]:
print("First Element = ", 
      rank_1_tensor[0].numpy())

First Element =  0


In [11]:
print("Last Element = ",
      rank_1_tensor[-1].numpy())

Last Element =  7


In [12]:
print("Element Before Last Element = ",
      rank_1_tensor[-2].numpy())

Element Before Last Element =  6


In [13]:
print("Element between first el & last el = ",
      rank_1_tensor[1:-1].numpy())

Element between first el & last el =  [1 2 3 4 5 6]


In [14]:
level_2_nested_list = [[1,2,3,4,5],
                       [6,7,8,9,0]]
rank_2_tensor = tf.constant(level_2_nested_list)
print(rank_2_tensor)

tf.Tensor(
[[1 2 3 4 5]
 [6 7 8 9 0]], shape=(2, 5), dtype=int32)


In [15]:
print("1st Level: ",
      rank_2_tensor[0].numpy())

1st Level:  [1 2 3 4 5]


In [16]:
print("1st Element in 1st level: ",
      rank_2_tensor[0, 0].numpy())

1st Element in 1st level:  1


In [17]:
print("4th Element in 2nd Level: ",
      rank_2_tensor[1, 3].numpy())

4th Element in 2nd Level:  9


### **Basic Operations with Tensors**

In [18]:
a = tf.constant([[0, 1],
                 [2, 4]])

b = tf.constant([[2, 3],
                 [4, 5]])

x = tf.constant([[5, 3],
                 [2, 1]], dtype= tf.float32)

y = tf.constant([[2, 7],
                 [9, 2]], dtype = tf.float32)

In [19]:
add_tens = tf.add(a, b)
print(add_tens)

tf.Tensor(
[[2 4]
 [6 9]], shape=(2, 2), dtype=int32)


In [20]:
# add_tensors = (x + y)
# print(add_tensors)
print(tf.add(x, y))

tf.Tensor(
[[ 7. 10.]
 [11.  3.]], shape=(2, 2), dtype=float32)


In [21]:
multiply_tens = (a * b)
print(multiply_tens)

tf.Tensor(
[[ 0  3]
 [ 8 20]], shape=(2, 2), dtype=int32)


In [22]:
multiply_tens = tf.multiply(x, y)
print(multiply_tens)

tf.Tensor(
[[10. 21.]
 [18.  2.]], shape=(2, 2), dtype=float32)


In [23]:
print(a * b)
print(tf.multiply(x, y))

tf.Tensor(
[[ 0  3]
 [ 8 20]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[10. 21.]
 [18.  2.]], shape=(2, 2), dtype=float32)


In [24]:
matmul_tensors = tf.matmul(a, b)
print(matmul_tensors)
print("\n########################################\n")
print(tf.matmul(x, y))

tf.Tensor(
[[ 4  5]
 [20 26]], shape=(2, 2), dtype=int32)

########################################

tf.Tensor(
[[37. 41.]
 [13. 16.]], shape=(2, 2), dtype=float32)


In [25]:
 c = tf.constant([[1,2,3],
                  [2,3,4],
                  [3,4,5]], dtype = tf.float32)
 
 m = tf.constant([[4,5,6],
                 [6,7,8],
                 [7,8,0]], dtype = tf.float32)
 
 print(tf.matmul(c,m))

tf.Tensor(
[[37. 43. 22.]
 [54. 63. 36.]
 [71. 83. 50.]], shape=(3, 3), dtype=float32)


In [26]:
# Finding Maximum
print("The Max value in the Tenosr object x: ",
      tf.reduce_max(x).numpy())

print("The Max value of a: ",
      tf.reduce_max(a))

The Max value in the Tenosr object x:  5.0
The Max value of a:  tf.Tensor(4, shape=(), dtype=int32)


In [27]:
# Finding the Minimum
print("The Minimum of b: ",
      tf.reduce_min(b).numpy())
print(b.numpy())

The Minimum of b:  2
[[2 3]
 [4 5]]


In [28]:
# Finding the Index position of maximum element
print("Index position of maximum in y: ",
      tf.argmax(y).numpy())
print(tf.reduce_max(y).numpy())
print(y.numpy())

Index position of maximum in y:  [1 0]
9.0
[[2. 7.]
 [9. 2.]]


In [29]:
# Finding the Index position of Minimum element in the Tensor
print("Maximum in a: ",
      tf.reduce_min(a).numpy())

print("Index position of Minimum in a: ",
      tf.argmin(a).numpy())
print(a.numpy())

Maximum in a:  0
Index position of Minimum in a:  [0 0]
[[0 1]
 [2 4]]


In [30]:
# Computing the softmax using softmax function
print("The softmax computation result in x: ",
      tf.nn.softmax(x).numpy())

The softmax computation result in x:  [[0.880797   0.11920292]
 [0.73105854 0.26894143]]


In [31]:
print("The softmax computation result in y: ",
      tf.nn.softmax(y).numpy())

The softmax computation result in y:  [[6.6928510e-03 9.9330717e-01]
 [9.9908900e-01 9.1105123e-04]]


In [32]:
print("The softmax can't compute in int32 dtype tensors")
print('Example')
print("softmax in a: ",
      tf.nn.softmax(a).numpy())
# This will throw an error

In [40]:
a = tf.constant([[1, 2, 3, 4, 5, 6]])
print("The shape of a: ", a.shape)

The shape of a:  (1, 6)


In [42]:
b = tf.reshape(a, [6,1])
print("The shape of b type a: ", b.shape)
print(b.numpy())

The shape of b type a:  (6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [44]:
c = tf.reshape(a, [3, 2])
print(c.shape)
print(c.numpy())

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [45]:
print("The shape of the flattend Tensor object: ", tf.reshape(a, [-1]))

The shape of the flattend Tensor object:  tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


**Broadcasting**

In [47]:
m = tf.constant([5])
n = tf.constant([[1, 2],
                [3, 4]])

print(tf.multiply(m, n))

tf.Tensor(
[[ 5 10]
 [15 20]], shape=(2, 2), dtype=int32)


In [48]:
ragged_list = [[1, 2, 3],
               [6],
               [2, 4, 1, 8, 3, 6],
               [3, 2, 9]]
            
ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)

<tf.RaggedTensor [[1, 2, 3], [6], [2, 4, 1, 8, 3, 6], [3, 2, 9]]>


In [49]:
string_tensor = tf.constant([["hii", "sarith", "u"],
                             ["yeah", "bithch", "y"]])

print(string_tensor)

tf.Tensor(
[[b'hii' b'sarith' b'u']
 [b'yeah' b'bithch' b'y']], shape=(2, 3), dtype=string)


In [51]:
sparse_tensor = tf.sparse.SparseTensor(indices=[[0,0], [2,2], [4,4]],
                                       values=[23, 56, 32],
                                       dense_shape=[5,5])
print(tf.sparse.to_dense(sparse_tensor))

tf.Tensor(
[[23  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0 56  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0 32]], shape=(5, 5), dtype=int32)
