<a href="https://colab.research.google.com/github/Sarith99/ML_Courses_Practicals/blob/main/Mastering_TensorFlow_%E2%80%9CVariables%E2%80%9D_in_5_Easy_Steps.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import tensorflow as tf

In [11]:
a = ([[0.0, 1.0],
      [2.0, 3.0]])

tens_a = tf.constant(a)
print(a)

[[0.0, 1.0], [2.0, 3.0]]


In [12]:
var_a = tf.Variable(tens_a)
print(var_a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0., 1.],
       [2., 3.]], dtype=float32)>


In [13]:
var_b = tf.Variable(100000000)
print(var_b.numpy())
print(var_b)

100000000
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=100000000>


In [14]:
c = [[1, 2, 3],
     [3, 4, 5]]
var_c = tf.Variable(c)
print(var_c)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5]], dtype=int32)>


In [15]:
var_d = tf.Variable("String Example")
print(var_d)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'String Example'>


In [16]:
e = ["Hii girls", 
     "Yooo",
     "hrewr"]
    
var_e = tf.Variable(e)
print(e)

['Hii girls', 'Yooo', 'hrewr']


In [17]:
a = tf.Variable([[1, 2, 3],
                [5, 6, 7]])

print("The values stored in the Variables: \n", a.value())
print("*****************************************************************************************")
print("The values stored in the Variables: \n", a.numpy())

The values stored in the Variables: 
 tf.Tensor(
[[1 2 3]
 [5 6 7]], shape=(2, 3), dtype=int32)
*****************************************************************************************
The values stored in the Variables: 
 [[1 2 3]
 [5 6 7]]


In [18]:
a = tf.Variable([[1, 2, 3],
                [5, 6, 7]])

print("The name of the Variable: ", a.name)

The name of the Variable:  Variable:0


In [19]:
print("The selected data type for the Variable: ", a.dtype)

The selected data type for the Variable:  <dtype: 'int32'>


In [21]:
a = tf.Variable([[1.0, 2.0],
                 [2.0,9.0]])

print("The shape of Variable: ", a.shape)
print("The No. of Diamensions: ", tf.rank(a).numpy())
print('The No. of Elements in Variable: ', tf.size(a).numpy())

The shape of Variable:  (2, 2)
The No. of Diamensions:  2
The No. of Elements in Variable:  4


**Operations**

In [23]:
a = tf.Variable([[4.0, 5.0],
                 [6.0, 7.0]])
print("Answer after adding by 2: \n", a+2)
print("Answer after subtracting by 2: \n", a-2)

Answer after adding by 2: 
 tf.Tensor(
[[6. 7.]
 [8. 9.]], shape=(2, 2), dtype=float32)
Answer after subtracting by 2: 
 tf.Tensor(
[[2. 3.]
 [4. 5.]], shape=(2, 2), dtype=float32)


In [24]:
a = tf.Variable([[1.0, 2.0],
                 [1.0, 2.0]])
print("Multiplication by 2: \n", a*2)
print("Division by 2: \n", a/2)

Multiplication by 2: 
 tf.Tensor(
[[2. 4.]
 [2. 4.]], shape=(2, 2), dtype=float32)
Division by 2: 
 tf.Tensor(
[[0.5 1. ]
 [0.5 1. ]], shape=(2, 2), dtype=float32)


**Matmul** and **Modulo** Operations: 

Finally, you can also do `matmul` and `modulo` operations with `@` and `%` signs:

In [27]:
a = tf.Variable([[1, 2],
                  [3, 4]])

print("Matmul with itself: \n", a@a)
print("Modulo by 2: \n", a%2)

Matmul with itself: 
 tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)
Modulo by 2: 
 tf.Tensor(
[[1 0]
 [1 0]], shape=(2, 2), dtype=int32)


In [29]:
a = tf.Variable([[1, 2],
                [3, 4]])

a.assign([[6, 7],
          [4, 2]])
print("a: \n", a)

a: 
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[6, 7],
       [4, 2]], dtype=int32)>


In [30]:
print("1st lavel: ", a[0].numpy())
print("2nd level: ", a[1].numpy())
print("last level: ", a[-1].numpy())

1st Element lavel:  [6 7]
2nd Element level:  [4 2]
last Element level:  [4 2]


In [34]:
print("1st Element in 2nd level: ", a[1, 0].numpy())
print("last element in Last level: ", a[-1,-1].numpy())

1st Element in 2nd level:  4
last element in Last level:  2


In [35]:
b = tf.Variable([[4, 5],
                 [3, 9]])
c = tf.Variable([2, 6])

print(b*c)

tf.Tensor(
[[ 8 30]
 [ 6 54]], shape=(2, 2), dtype=int32)


In [38]:
x = tf.Variable([1, 2],
                [2, 1])

print(tf.reshape(a, (4,1)))
print("$$$$$$$$$$$$$$$$$$$$$$$$$$")
print(tf.reshape(a, (1,4)))

tf.Tensor(
[[6]
 [7]
 [4]
 [2]], shape=(4, 1), dtype=int32)
$$$$$$$$$$$$$$$$$$$$$$$$$$
tf.Tensor([[6 7 4 2]], shape=(1, 4), dtype=int32)


In [39]:
a = tf.Variable([[1, 2], [2, 3]])

print("The device which processes the Variable: \n", a.device)

The device which processes the Variable: 
 /job:localhost/replica:0/task:0/device:CPU:0


In [41]:
with tf.device('GPU:0'):
  k = a * b
  print("The cevice processes the claculation: \n", k.device)
  print("K: \n",k)

The cevice processes the claculation: 
 /job:localhost/replica:0/task:0/device:GPU:0
K: 
 tf.Tensor(
[[ 4 10]
 [ 6 27]], shape=(2, 2), dtype=int32)
