<a href="https://colab.research.google.com/github/Sarith99/ML_Courses_Practicals/blob/main/ML_Course_Practical_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello World")

Hello World


In [ ]:
def HelloWorldXY(x, y):
  if(x<10):
    print("Hello World, x was < 10")
  elif(x<20):
    print("Hello World, x was >= 10 but < 20")
  else:
    print("Hello World, x was >= 20")
  return x+y
  
for i in range(8, 25, 5): # i=8, 13, 18, 23 (start, stop, step)
  print("---Now Running with i: {}".format(i))
  r = HelloWorldXY(i,i)
  print("Result from HelloWorld: {}".format(i,r))

---Now Running with i: 8
Hello World, x was < 10
Result from HelloWorld: 8
---Now Running with i: 13
Hello World, x was >= 10 but < 20
Result from HelloWorld: 13
---Now Running with i: 18
Hello World, x was >= 10 but < 20
Result from HelloWorld: 18
---Now Running with i: 23
Hello World, x was >= 20
Result from HelloWorld: 23


In [ ]:
print(HelloWorldXY(1,2))

Hello World, x was < 10
3


In [ ]:
print("Iterate over the items. `range(2)` is like a list[0,1].")
for i in range(2):
  print(i)

print("Iterate over actual list.")
for i in [0,1]:
  print(i)

print("While works.")
i = 0
while i < 2:
  print(i)
  i += 1

Iterate over the items. `range(2)` is like a list[0,1].
0
1
Iterate over actual list.
0
1
While works.
0
1


In [ ]:
print("Python supports standard key words like continue and break")
while True:
  print("Entered While")
  break

Python supports standard key words like continue and break
Entered While


# **Numpy and Lists**
Python has lists built into the language. However, we will use a library called numpy for this. Numpy gives you lot's of support functions that are useful when doing Machine Learning.

Here, you will also see an import statement. This statement makes the sntire numpy package available and we can access those symbols using the abbreviated 'np'syntax.

In [ ]:
import numpy as np

# Create a numpy array, and append an element.
a = np.array(["Hello", "World"])
a = np.append(a, "!")
print("Current array: {}".format(a))
print("Printing each element")
for i in a:
  print(i)

print("\nPrinting each element and their index")
for i,e in enumerate(a):
  print("Index: {}, was: {}".format(i,e))

Current array: ['Hello' 'World' '!']
Printing each element
Hello
World
!

Printing each element and their index
Index: 0, was: Hello
Index: 1, was: World
Index: 2, was: !


In [ ]:
print("\nShowing some basic math on arrays")
b = np.array([0,1,4,2,3])
print("Max: {}".format(np.max(b)))
print("Average: {}".format(np.average(b)))
print("Max index: {}".format(np.argmax(b)))


Showing some basic math on arrays
Max: 4
Average: 2.0
Max index: 2


In [ ]:
print("\nYou can print the type of anything")
print("Type of b: {}, type of b[0]: {}".format(type(a), type(a[0])))


You can print the type of anything
Type of b: <class 'numpy.ndarray'>, type of b[0]: <class 'numpy.str_'>


In [ ]:
print("\nUse numpy to create a [3,3] dimension array with random number")
c = np.random.rand(3, 3)
print(c)


Use numpy to create a [3,3] dimension array with random number
[[0.8307627  0.08111329 0.82140078]
 [0.00869833 0.54884708 0.72972968]
 [0.91293183 0.79677406 0.95348876]]


In [ ]:
print("\nYou can print the dimensions of arrays")
print("Shape of a: {}".format(a.shape))
print("Shape of b: {}".format(b.shape))
print("Shape of c: {}".format(c.shape))
print("...Observe, Python uses both [0,1,2] and (0,1,2) to specify lists")


You can print the dimensions of arrays
Shape of a: (3,)
Shape of b: (5,)
Shape of c: (3, 3)
...Observe, Python uses both [0,1,2] and (0,1,2) to specify lists


# **Colab Specifics**

Colab is virtual machine you can see access directly. To run commands at the VM's terminal, prefix the line with an exclamation point (!).

In [ ]:
print("\nDoing $ls on filesystem")
!ls -l
!pwd


Doing $ls on filesystem
total 4
drwxr-xr-x 1 root root 4096 Apr 19 14:23 sample_data
/content


In [ ]:
print("Install numpy") # Just for test, numpy is already installed in all colab instances.
!pip install numpy

Install numpy
